### ISSUE TITLE
Failed to process platform discovery. Fix the problem and restart the service.

### ISSUE THREAD

**Issue by mese16** [aurc/melview-mitsubishi-au-nz#6]
**Describe Your Problem:**
I have following message when Homebridge starts. I installed the plugin for the first time.
[6.1.2022, 12:43:33] [MitsubishiAUNZ] Failed to process platform discovery. Fix the problem and restart the service.

**Logs:**
[6.1.2022, 12:43:33] [MitsubishiAUNZ] Failed to process platform discovery. Fix the problem and restart the service.
```

{
    "bridge": {
        "name": "Homebridge 883E",
        "username": "***********",
        "port": 5**1,
        "pin": "551-******"
    },
    "accessories": [
        {
            "name": "Pihole",
            "auth": "****************",
            "ssl": false,
            "rejectUnauthorized": true,
            "host": "192.*********",
            "port": 80,
            "baseDirectory": "/admin/",
            "time": 0,
            "reversed": true,
            "logLevel": 1,
            "accessory": "Pihole"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Phoscon",
            "anyOn": true,
            "effects": true,
            "excludeSensorTypes": [
                "CLIP"
            ],
            "hosts": [
                "127.0.0.1:80"
            ],
            "lights": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "resource": true,
            "sensors": true,
            "wallSwitch": true,
            "platform": "Hue"
        },
        {
            "name": "FritzPlatform",
            "warn": true,
            "error": true,
            "extendedError": true,
            "devices": [
                {
                    "active": true,
                    "name": "Fritzbox",
                    "host": "192.********",
                    "username": "********",
                    "password": "**********",
                    "ssl": true,
                    "tr064": true,
                    "igd": false,
                    "model": "7590",
                    "wifiUnits": 2,
                    "master": true,
                    "hide": true,
                    "connection": "cable",
                    "options": {
                        "wifi_guest": "switch",
                        "wps": "switch",
                        "broadband": "characteristic"
                    }
                }
            ],
            "presence": [
                {
                    "active": true,
                    "name": "Claudia in House",
                    "address": "192.1*******",
                    "accType": "occupancy"
                }
            ],
            "smarthome": [
                {
                    "active": false
                }
            ],
            "callmonitor": {
                "active": true,
                "ip": "1*******",
                "port": 1012,
                "incomingFrom": [
                    "+*******",
                    "+********",
                    "+*********",
                    "+*********"
                ]
            },
            "options": {
                "polling": {
                    "timer": 15
                }
            },
            "platform": "FritzPlatform"

        },
        {
            "user": "********",
            "password": "***********",
            "dry": false,
            "platform": "MitsubishiAUNZ"
        }
    ],
    "disabledPlugins": [
        "homebridge-mhacwifi1-lan"
    ]
}


**Environment:**

* **Plugin Version**: 1.2.6
* **Homebridge Version**: 1.3.9
* **Node.js Version**: v16.13.0
* **NPM Version**: v8.1.0
* **Operating System**: Raspbian

**Comment by aurc** [comment]
Could you please enable debug mode. I suspect the problem might be that the
aircon units are not in the same subnet as Homebridge or not reachable…

**Comment by mese16** [comment]
Hi, thanks for your suport. 

So i can successfully ping the aircon from the raspi.

6.1.2022, 13:03:21] [MitsubishiAUNZ] Failed to process platform discovery. Fix the problem and restart the service.
[6.1.2022, 13:03:21] [MitsubishiAUNZ] SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at MelviewService.discover (/usr/lib/node_modules/homebridge-airconditioner-mitsubishi-au-nz/src/melviewService.ts:80:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at MelviewMitsubishiHomebridgePlatform.discoverDevices (/usr/lib/node_modules/homebridge-airconditioner-mitsubishi-au-nz/src/platform.ts:71:19)

**Comment by aurc** [comment]
Hmm… Ok, I have to release a new version with a debug message showing the
bad JSON being received to figure it out. In the meantime, could you please
let me know a few things?
- are you in NZ or Australia?
- what’s the AC unit?
- what’s the Wi-Fi module?

Please allow some 2 days for me to push these changes that can give us
further information on your issue.

Cheers

**Comment by mese16** [comment]
- I'm living in Switzerland. Does it just work for NZ or AU?
- MSZ-HR50VF
- MAC-567IF-E

**Comment by aurc** [comment]
Correct, only for AU and NZ! The cloud service under the hood for
Mitsubishi units is different in different geographic locations, and have
different specs and data formats. That then explains the failure to parse
the data, as it might not be receiving a JSON at all.

In that case, I will close the issue.  Sorry for that… You may want to find
a plug-in in your region.
